### ISSUE TITLE
Major issues with semantic versioning.

### ISSUE THREAD

**Issue by regexident** [mrackwitz/Version#10]
1. Version allows optional minor/patch components, semver does not. (§2: “A normal version number MUST take the form X.Y.Z")

2. Version allows leading zeros, semver does not. (§2: “X, Y, and Z are non-negative integers, and MUST NOT contain leading zeroes”, http://semver.org/)

3. Version includes build in comparisons, semver does not. (§10: “Build metadata SHOULD be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence.”, http://semver.org/)

Apart from being incompatible with semver, these changes lead to more complicated code.
Complicated code that is prone to bug. Complicated code that led to bugs. Several.

4. The Regex.groupsOfFirstMatch method omits nil-groups. This causes Version(“1.0-alpha”) to not have an alpha (as the “alpha" is returned at the position of patch and not being a valid integer value gets turned into nil for patch and not be considered for prerelease at all).

5. Even if the version number was parsed properly, we have bugs in “func<“, "func==“ and “hashValue”: “1.0” should be equal to “1.0.0”. It isn’t though, according to Version (it’s considered less-than).

I'm working on a PR.

**Comment by mrackwitz** [comment]
This was fixed afaict by manually merging the changes from #11.
