### ISSUE TITLE
Error on extension UIDevice 

### ISSUE THREAD

**Issue by baquiax** [mrackwitz/Version#15]
I'm trying to use Version (0.4.0) on Xcode 7.3.1 but when I compile my project it gives me an issue:

`Version.swift:271:33: Cannot convert value of type 'Version?' to expected argument type 'String'`

**Comment by mrubin** [comment]
I still get `Version.swift:272:33: error: cannot convert value of type 'Version?' to expected argument type 'String'`

Could you please temporarily remove/comment out the UIDevice extension and put out a working release?

**Comment by mrackwitz** [comment]
Closed via 6275635ff52ea2d6cdcdbc1bb5931f4bfb202b0b.
