### ISSUE TITLE
Manual Installation

### ISSUE THREAD

**Issue by lfarah** [mrackwitz/Version#17]
`CocoaPods` and `Carthage` are awesome tools and make our life really easier, but there are some devs who still don't know how to use them. 

It would be cool to add the _Manual installation_ guide in your `README.md`. You can take a look at my [iOS Readme Template](https://github.com/awesome-labs/iOS-readme-template) to see how you can do it.

**Comment by regexident** [comment]
I'm not sure I would want to make manual installation an "officially endorsed" install method.
Manual installation is hardly ever the best (or even just a good) choice when it comes to dependency managing beyond the scope of quick 'n' dirty scripting/prototyping.

If you don't know how to use SPM/Carthage/CocoaPods, then the proper way to integrate "Version" is to first learn about dependency managing and then come back and use one of the officially supported methods. :wink:
