### ISSUE TITLE
Error comparing versions?

### ISSUE THREAD

**Issue by niklassaers** [mrackwitz/Version#19]
(lldb) po requiredVersion
▿ 0.0.15
- major : 0
  ▿ minor : Optional<Int>

```
- Some : 0 { ... }
```

  ▿ patch : Optional<Int>
    - Some : 15
- prerelease : nil
- build : nil

(lldb) po requiredVersion > "2.2.0"
true

(lldb) po requiredVersion < "2.2.0"
true

These last two comparisons surprised me. I expected 0.0.15 < 2.2.0

Using 0.5.0 from CocoaPods

**Comment by regexident** [comment]
Thanks @niklassaers, this has been fixed in 751b1580fce0198c1ec8db0a8b1d7ce4ec66d421. 🙂
