### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by wuf810** [mrackwitz/Version#22]
Ticket for Swift 3 compatibility

**Comment by neoneye** [comment]
I think the best swift3 migration is by @opwoco [here](https://github.com/opwoco/Version). He has added a few **FIXME**'s related to comparison operators.

**Comment by wuf810** [comment]
Hey thanks @neoneye, I'll check it out

**Comment by regexident** [comment]
As of 4229aa559cc9edc3a09f281bd0c606194bc594ba Version supports Swift 3.2, while 94293e424b5645f2873f83cd28061427c6bcccf4 improves the readability & maintainability of the version parser and 751b1580fce0198c1ec8db0a8b1d7ce4ec66d421 fixes a bug in the comparison logic.

(Having been added as a collaborator recently I will try to keep Version up-to-date in a more timely manner)

**Comment by neoneye** [comment]
Great job @regexident
