### ISSUE TITLE
Improve seo

### ISSUE THREAD

**Issue by ianbytchek** [mrackwitz/Version#28]
Most popular maintained repo, yet hard to find! Great work by the way! ✌️

![2018-01-30 01 40 25](https://user-images.githubusercontent.com/1086845/35535987-e0054f8c-055e-11e8-81c2-d07d01cbc199.gif)

**Comment by regexident** [comment]
Good point, Ian.

Any ideas for how we could improve this?

This is Version's current headline:
> "Version represents and compares semantic versions in Swift."

Do you think something like this would be an improvement?
> "Represent and compare versions via semantic versioning (SemVer) in Swift"

It should now show up for:
- "version" & "versions"
- "semantic versioning" & "SemVer"
- "Swift"
- …

cc @mrackwitz

**Comment by ianbytchek** [comment]
Try `semver`, `semantic`, `version` tags – I think it would be enough. Second headline is 💯 more informative.

**Comment by regexident** [comment]
Tags, a good point!

I'll have to forward this to @mrackwitz, as I don't have the required privileges to change those things.

**Comment by mrackwitz** [comment]
Done! 👍  Thanks! ❤️
