### ISSUE TITLE
Fails to build with Carthage

### ISSUE THREAD

**Issue by ianbytchek** [mrackwitz/Version#29]
Judging by #14 this used to work with Carthage once upon a time, but currently fails. Would love to see it working again! 😍

Last line of log file:

> The following build commands failed:
	ProcessInfoPlistFile /Users/ianbytchek/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/version/0.6.1/Build/Intermediates.noindex/ArchiveIntermediates/Version/IntermediateBuildFilesPath/UninstalledProducts/macosx/Version.framework/Versions/A/Resources/Info.plist Version/Info.plist

**Comment by regexident** [comment]
Should be fixed with v0.6.2 / PR #30.

Could you confirm with me that it works for you?

**Comment by ianbytchek** [comment]
Oooaaah yeeaah! 🍻 Another issue though, hopefully just a config twitch:

> Error:(7, 8) module file's minimum deployment target is OS X v10.13: /Carthage/Build/Mac/Version.framework/Modules/Version.swiftmodule/x86_64.swiftmodule

**Comment by regexident** [comment]
> Don't think there's anything that has critical dependencies on most recent API? I need 10.11 at least, but pretty sure it will compile equally fine for 10.10.

Solved in 0.6.3 (CocoaPods)
