### ISSUE TITLE
EXC_BAD_INSTRUCTION when comparing

### ISSUE THREAD

**Issue by MattesGroeger** [mrackwitz/Version#5]
I keep getting this crash when comparing semantic versions with your latest CocoaPods release `0.2.0`.

Even on the command line it crashes Xcode when doing e.g.:
```
p NSBundle.mainBundle().shortVersion! < "1.0.0"
```

Any idea what's going on? I'm using Xcode Version 6.1.1 (6A2008a).

**Comment by tsuharesu** [comment]
Same here... can't understand why, because the tests are fine. And the implementation seems fine too...

**Comment by mrackwitz** [comment]
It's not unlikely that this was an issue caused by the compiler. This doesn't seem to be relevant anymore.
